import type { Metadata } from "next";

import { getCategories, getShopProducts, listProducts, searchSuggestions } from "@/lib/catalog";
import { rankProducts } from "@/lib/search";
import { paletteColor } from "@/lib/product-options";
import {
  breadcrumbList,
  collectionPageJsonLd,
  itemListJsonLd,
  listingDescription,
  listingTitle,
} from "@/lib/seo";
import { FilterBar } from "@/components/shop/FilterBar";
import { ProductGrid } from "@/components/product/ProductGrid";
import { PageIntro } from "@/components/ui/PageIntro";
import { isLocale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { t as pick } from "@/lib/format";
import type { Locale, ProductFilters } from "@/types";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;

/**
 * A title that says which listing this is.
 *
 * Every filtered listing used to share one title — "Shop" — so a category, a
 * colour and a search result were indistinguishable in a browser's history, in
 * a shared link, and to a crawler, which treats a hundred URLs under one title
 * as duplicates and indexes none of them.
 *
 * The canonical is the deliberate part. A filtered listing is a *view* of a
 * category, not a page of its own, so `?color=cobalt&sort=price-asc` all point
 * at the category — otherwise the same twelve products compete with themselves
 * across dozens of URLs. A search result is marked `noindex` outright: it is
 * generated by whatever somebody typed, and there is no end to it.
 */
export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ locale: string }>;
  searchParams: SearchParams;
}): Promise<Metadata> {
  const [{ locale: raw }, query] = await Promise.all([params, searchParams]);
  const locale: Locale = isLocale(raw) ? raw : "en";
  const t = getDictionary(locale);

  const [categories, allProducts] = await Promise.all([getCategories(), getShopProducts()]);
  const categorySlug = one(query.category);
  const category = categories.find((c) => c.slug === categorySlug);
  const term = one(query.q)?.trim();

  const colorNames = many(query.color)
    .map((id) => paletteColor(id)?.name[locale])
    .filter((name): name is string => Boolean(name));

  const count = category
    ? allProducts.filter((product) => product.categoryPath.includes(category.id)).length
    : allProducts.length;

  const title = listingTitle({
    categoryName: category ? pick(category.name, locale) : undefined,
    searchTerm: term,
    colorNames,
    onSale: one(query.onSale) === "true",
    fallback: t.nav.shop,
    locale,
  });

  const description = listingDescription({
    categoryDescription: category?.description ? pick(category.description, locale) : undefined,
    count,
    categoryName: category ? pick(category.name, locale) : undefined,
    fallback: t.shop.collectionBody,
    locale,
  });

  const canonicalPath = category ? `/${locale}/shop?category=${category.slug}` : `/${locale}/shop`;

  return {
    title,
    description,
    alternates: { canonical: canonicalPath },
    ...(term ? { robots: { index: false, follow: true } } : {}),
  };
}

export const revalidate = 3600;

/** Normalise a param that may arrive as a string, an array, or not at all. */
function many(value: string | string[] | undefined): string[] {
  if (!value) return [];
  return Array.isArray(value) ? value : [value];
}

function one(value: string | string[] | undefined): string | undefined {
  if (!value) return undefined;
  return Array.isArray(value) ? value[0] : value;
}

export default async function ShopPage({
  params,
  searchParams,
}: {
  params: Promise<{ locale: string }>;
  searchParams: SearchParams;
}) {
  const [{ locale: raw }, query] = await Promise.all([params, searchParams]);
  const locale: Locale = isLocale(raw) ? raw : "en";
  const t = getDictionary(locale);

  // Facets are built from the visible set: a colour filter that returns
  // nothing because every product carrying it is in the seasonal warehouse is
  // a filter that looks broken.
  const [categories, allProducts] = await Promise.all([getCategories(), getShopProducts()]);

  const categorySlug = one(query.category);
  const category = categories.find((c) => c.slug === categorySlug);

  const filters: ProductFilters = {
    categoryIds: category ? [category.id] : undefined,
    colorIds: many(query.color),
    sizeIds: many(query.size),
    minPrice: one(query.minPrice) ? Number(one(query.minPrice)) : undefined,
    maxPrice: one(query.maxPrice) ? Number(one(query.maxPrice)) : undefined,
    inStockOnly: one(query.inStock) === "true",
    sort: (one(query.sort) as ProductFilters["sort"]) ?? "featured",
  };

  let products = await listProducts(filters);

  // `onSale` is a presentation filter rather than a catalogue facet, so it is
  // applied here instead of widening the `ProductFilters` contract.
  if (one(query.onSale) === "true") {
    products = products.filter((p) => p.compareAtPrice && p.compareAtPrice > p.price);
  }

  const badge = one(query.badge);
  if (badge) {
    products = products.filter((p) => p.badges.includes(badge as never));
  }

  /*
   * The search term is applied last, over the filtered set.
   *
   * Ordering it this way means "coats" plus a search for "wool" narrows to
   * wool coats, rather than the search throwing the category away. It also
   * keeps the ranking meaningful: the list handed to `rankProducts` is already
   * only what the shopper asked to see.
   *
   * Until now `?q=` did nothing at all on this page — search existed only as
   * the header's dropdown, so there was no results page to link to, share, or
   * land on from a search engine.
   */
  const term = one(query.q)?.trim() ?? "";
  if (term) products = rankProducts(products, term, 60);

  // Near-misses, only when the search found nothing. A dead end that says only
  // "no results" is where a shopper leaves.
  const suggestions = term && products.length === 0 ? await searchSuggestions(term, locale) : [];

  const heading = listingTitle({
    categoryName: category ? pick(category.name, locale) : undefined,
    searchTerm: term || undefined,
    fallback: t.shop.collectionTitle,
    locale,
  });

  const crumbs = [
    { name: "net sale", path: "" },
    { name: t.nav.shop, ...(category || term ? { path: "shop" } : {}) },
    ...(category ? [{ name: pick(category.name, locale) }] : []),
    ...(term && !category ? [{ name: heading }] : []),
  ];

  return (
    <>
      {/*
        Structured data for the listing.

        A search result page deliberately gets none: the markup describes a
        curated collection, and a page generated from whatever somebody typed
        is not one. Claiming otherwise is the kind of mismatch that costs a
        site its rich results everywhere else.
      */}
      {!term && (
        <script
          type="application/ld+json"
          // Serialised from our own catalogue, never from user input.
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([
              collectionPageJsonLd({
                name: heading,
                description: category?.description ? pick(category.description, locale) : "",
                path: category ? `shop?category=${category.slug}` : "shop",
                locale,
              }),
              breadcrumbList(crumbs, locale),
              itemListJsonLd(products.slice(0, 24), locale, heading),
            ]),
          }}
        />
      )}

      <PageIntro
        locale={locale}
        eyebrow={term ? t.nav.search : category ? t.shop.category : t.shop.allPieces}
        title={term ? heading : category ? pick(category.name, locale) : t.shop.collectionTitle}
        description={
          term
            ? `${products.length} ${t.shop.results}`.trim()
            : category?.description
              ? pick(category.description, locale)
              : t.shop.collectionBody
        }
      />

      <FilterBar
        categories={categories}
        products={allProducts}
        resultCount={products.length}
        locale={locale}
      />

      <div className="ns-container py-10 md:py-16">
        <ProductGrid
          products={products}
          locale={locale}
          columns={4}
          priorityCount={4}
          emptyState={
            <div className="mx-auto max-w-sm">
              <p className="text-ink font-display text-lg font-semibold">{t.shop.emptyTitle}</p>
              <p className="text-smoke mt-2 text-[0.9375rem]">
                {term ? t.shop.searchEmptyBody : t.shop.emptyBody}
              </p>

              {/*
                What the shop actually calls things. Offering the nearest words
                in the catalogue turns a dead end into a next step, and quietly
                teaches the vocabulary this shop uses.
              */}
              {suggestions.length > 0 && (
                <p className="mt-4 flex flex-wrap justify-center gap-2">
                  {suggestions.map((suggestion) => (
                    <a
                      key={suggestion}
                      href={`/${locale}/shop?q=${encodeURIComponent(suggestion)}`}
                      className="border-line hover:border-ink text-ink rounded-pill border px-3 py-1.5 text-[0.8125rem] transition-colors"
                    >
                      {suggestion}
                    </a>
                  ))}
                </p>
              )}
            </div>
          }
        />
      </div>
    </>
  );
}
