/**
 * net sale — brand asset generator.
 *
 *   node scripts/generate-brand.mjs
 *
 * Single source of truth for every piece of brand geometry on the site. Reads
 * `scripts/brand-paths.json` (cubic bezier outlines traced from the master logo
 * artwork, normalised to a 120x120 box) and emits:
 *
 *   public/brand/net-sale-mark.svg        light-ground mark
 *   public/brand/net-sale-mark-light.svg  dark-ground mark
 *   public/brand/net-sale-mark-ink.svg    single-colour, for print and favicons
 *   public/brand/net-sale-icon.svg        padded square favicon
 *   public/lottie/net-sale-wave.json      morphing pebble + ripple rings
 *   src/components/brand/paths.ts         typed path constants for React/Motion
 *
 * The monogram is **knocked out** of the pebble in the artwork — the N is a
 * hole, not a drawn shape — so it is rendered in the ground colour on top of
 * the blob rather than as a separate coloured mark. That is what lets the same
 * geometry sit on cream, on ink, or on red without re-cutting the artwork.
 *
 * Re-run this after re-tracing. Never hand-edit the outputs: the wave variants
 * must keep an identical command sequence to the base blob or Motion can no
 * longer interpolate between them.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const B = JSON.parse(readFileSync(join(__dirname, "brand-paths.json"), "utf8"));

/** Sampled from the supplied palette swatch. */
const RED = "#CE1212";
const RED_DEEP = "#810000";
const INK = "#1B1717";
const CREAM = "#EEEBDD";

/* ========================================================================== */
/*  SVG                                                                       */
/* ========================================================================== */

const monoPaths = (fill) =>
  B.monogram.map((d) => `  <path d="${d}" fill="${fill}"/>`).join("\n");

const mark = (blob, mono, dot) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${B.viewBox}" fill="none" role="img" aria-label="net sale">
  <path d="${B.blob}" fill="${blob}"/>
  <path d="${B.dot}" fill="${dot}"/>
${monoPaths(mono)}
</svg>
`;

function writeSvgs() {
  const dir = join(ROOT, "public", "brand");
  mkdirSync(dir, { recursive: true });

  // On cream: red pebble, cream N knocked out of it.
  writeFileSync(join(dir, "net-sale-mark.svg"), mark(RED, CREAM, RED));
  // On ink: identical, with the N cut to the dark ground.
  writeFileSync(join(dir, "net-sale-mark-light.svg"), mark(RED, INK, RED));
  // Single colour, for embroidery, stamps and anywhere red is unavailable.
  writeFileSync(join(dir, "net-sale-mark-ink.svg"), mark(INK, CREAM, INK));

  writeFileSync(
    join(dir, "net-sale-icon.svg"),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-6 -6 132 132" fill="none">
  <rect x="-6" y="-6" width="132" height="132" rx="30" fill="${INK}"/>
  <path d="${B.blob}" fill="${RED}"/>
  <path d="${B.dot}" fill="${RED}"/>
${B.monogram.map((d) => `  <path d="${d}" fill="${INK}"/>`).join("\n")}
</svg>
`,
  );

  return 4;
}

/* ========================================================================== */
/*  paths.ts                                                                  */
/* ========================================================================== */

function writePathsModule() {
  const file = join(ROOT, "src", "components", "brand", "paths.ts");
  mkdirSync(dirname(file), { recursive: true });

  writeFileSync(
    file,
    `/**
 * net sale — brand geometry.
 *
 * GENERATED by \`scripts/generate-brand.mjs\`. Do not edit by hand: re-trace the
 * master artwork, update \`scripts/brand-paths.json\`, and re-run the script.
 *
 * Vector data traced from the master logo artwork and normalised to a 120x120
 * viewBox. Every entry in \`BLOB_WAVES\` shares an identical command sequence
 * with the base blob, which is what lets Motion interpolate the \`d\` attribute
 * between them — break that and the morph silently stops working.
 */

/** Shared viewBox for every mark path below. */
export const NS_VIEWBOX = "${B.viewBox}";

/** Visual centre of the pebble — the origin for ripples, orbits and scaling. */
export const NS_CENTROID = { x: ${B.centroid[0]}, y: ${B.centroid[1]} } as const;

/** Outer organic pebble silhouette. */
export const BLOB = "${B.blob}";

/** The detached dot — the full stop of the wordmark. */
export const DOT = "${B.dot}";

/**
 * The N, in two parts: the zigzag stem and the rounded bar above it.
 *
 * In the artwork the monogram is *knocked out* of the pebble, so these are
 * painted in the surrounding ground colour rather than in a brand colour. That
 * is what lets one piece of geometry sit correctly on cream, on ink and on red.
 */
export const MONOGRAM = [
${B.monogram.map((d) => `  "${d}",`).join("\n")}
] as const;

/**
 * Four wave states of the pebble. Index 0 is the true logo; 1-3 are radial
 * sinusoidal deformations. Cycling 0>1>2>3>0 reads as a soft breathing wave.
 */
export const BLOB_WAVES = [
${B.waves.map((w) => `  "${w}",`).join("\n")}
] as const;

/** Brand constants mirrored from \`globals.css\` for canvas and SVG use. */
export const BRAND = {
  red: "${RED}",
  redDeep: "${RED_DEEP}",
  ink: "${INK}",
  cream: "${CREAM}",
} as const;
`,
  );
}

/* ========================================================================== */
/*  Lottie                                                                    */
/* ========================================================================== */

const SIZE = 512;
const SRC = 120;
const S = SIZE / SRC;
const FPS = 60;
const DUR = 240; // 4s loop
const OFF = [(SIZE - SRC * S) / 2, (SIZE - SRC * S) / 2];
const CENTER = [B.centroid[0] * S + OFF[0], B.centroid[1] * S + OFF[1]];

/** Parse an SVG cubic path into its segments. */
function parsePath(d) {
  const tokens = d.match(/[MCZLmczl]|-?\d*\.?\d+/g) || [];
  const segs = [];
  let cmd = null;
  let i = 0;
  let cur = [0, 0];
  const num = () => parseFloat(tokens[i++]);

  while (i < tokens.length) {
    const tk = tokens[i];
    if (/[MCZLmczl]/.test(tk)) {
      cmd = tk;
      i++;
      if (cmd === "Z" || cmd === "z") continue;
    }
    if (cmd === "M" || cmd === "m") {
      cur = [num(), num()];
    } else if (cmd === "C" || cmd === "c") {
      const c1 = [num(), num()];
      const c2 = [num(), num()];
      const to = [num(), num()];
      segs.push({ from: cur, c1, c2, to });
      cur = to;
    } else if (cmd === "L" || cmd === "l") {
      const to = [num(), num()];
      segs.push({ from: cur, c1: cur, c2: to, to });
      cur = to;
    } else {
      i++;
    }
  }
  return segs;
}

/**
 * Convert an SVG path to Lottie bezier data.
 * Lottie stores tangents *relative* to their vertex where SVG stores absolute
 * control points — that subtraction is the whole conversion.
 */
function toLottieShape(d, scale = S, offset = OFF) {
  const segs = parsePath(d);
  if (!segs.length) return { i: [], o: [], v: [], c: true };

  const sc = (p) => [p[0] * scale + offset[0], p[1] * scale + offset[1]];
  const v = [];
  const o = [];
  const inT = [];

  for (let k = 0; k < segs.length; k++) {
    const seg = segs[k];
    const from = sc(seg.from);
    const c1 = sc(seg.c1);
    v.push(from);
    o.push([c1[0] - from[0], c1[1] - from[1]]);

    const prev = segs[(k - 1 + segs.length) % segs.length];
    const pc2 = sc(prev.c2);
    inT.push([pc2[0] - from[0], pc2[1] - from[1]]);
  }
  return { i: inT, o, v, c: true };
}

const hex = (h) => {
  const n = parseInt(h.replace("#", ""), 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255, 1];
};

const RED_RGB = hex(RED);
const CREAM_RGB = hex(CREAM);

const sv = (k, ix = 1) => ({ a: 0, k, ix });
const shapeProp = (shape, ix = 1) => ({ a: 0, k: shape, ix });

function av(keys, ix = 1) {
  return {
    a: 1,
    ix,
    k: keys.map((kf, idx) => ({
      t: kf.t,
      s: Array.isArray(kf.s) ? kf.s : [kf.s],
      ...(idx < keys.length - 1
        ? { i: { x: [0.22], y: [1] }, o: { x: [0.36], y: [0] } }
        : {}),
    })),
  };
}

function transform({ s = [100, 100], o = 100, r = 0 }) {
  return {
    o: typeof o === "number" ? sv(o, 11) : o,
    r: typeof r === "number" ? sv(r, 10) : r,
    p: { a: 0, k: [...CENTER, 0], ix: 2 },
    a: { a: 0, k: [...CENTER, 0], ix: 1 },
    s: Array.isArray(s) ? { a: 0, k: [...s, 100], ix: 6 } : s,
  };
}

const trGroup = () => ({
  ty: "tr",
  p: { a: 0, k: [0, 0], ix: 2 },
  a: { a: 0, k: [0, 0], ix: 1 },
  s: { a: 0, k: [100, 100], ix: 3 },
  r: sv(0, 6),
  o: sv(100, 7),
  nm: "transform",
});

const fillGroup = (shapeKs, color) => [
  {
    ty: "gr",
    nm: "group",
    it: [
      { ty: "sh", ix: 1, nm: "path", ks: shapeKs },
      { ty: "fl", c: { a: 0, k: color, ix: 4 }, o: sv(100, 5), r: 1, nm: "fill" },
      trGroup(),
    ],
  },
];

const strokeGroup = (shapeKs, color, width) => [
  {
    ty: "gr",
    nm: "group",
    it: [
      { ty: "sh", ix: 1, nm: "path", ks: shapeKs },
      {
        ty: "st",
        c: { a: 0, k: color, ix: 3 },
        o: sv(100, 4),
        w: sv(width, 5),
        lc: 2,
        lj: 2,
        nm: "stroke",
      },
      trGroup(),
    ],
  },
];

const layer = (nm, ind, shapes, ks) => ({
  ddd: 0,
  ind,
  ty: 4,
  nm,
  sr: 1,
  ks,
  ao: 0,
  bm: 0,
  shapes,
  ip: 0,
  op: DUR,
  st: 0,
});

function buildLottie() {
  const waves = B.waves.map((w) => toLottieShape(w));
  const dot = toLottieShape(B.dot);
  const mono = B.monogram.map((d) => toLottieShape(d));

  const morph = {
    a: 1,
    ix: 2,
    k: [
      { t: 0, s: [waves[0]], i: { x: 0.22, y: 1 }, o: { x: 0.36, y: 0 } },
      { t: DUR * 0.25, s: [waves[1]], i: { x: 0.22, y: 1 }, o: { x: 0.36, y: 0 } },
      { t: DUR * 0.5, s: [waves[2]], i: { x: 0.22, y: 1 }, o: { x: 0.36, y: 0 } },
      { t: DUR * 0.75, s: [waves[3]], i: { x: 0.22, y: 1 }, o: { x: 0.36, y: 0 } },
      { t: DUR, s: [waves[0]] },
    ],
  };

  const monoScale = av(
    [
      { t: 0, s: [100, 100] },
      { t: DUR * 0.5, s: [104, 104] },
      { t: DUR, s: [100, 100] },
    ],
    6,
  );

  const layers = [];
  let ind = 1;

  // Painted front to back: Lottie draws the first layer on top.
  layers.push(
    layer(
      "dot",
      ind++,
      fillGroup(shapeProp(dot), RED_RGB),
      transform({
        s: av(
          [
            { t: 0, s: [100, 100] },
            { t: DUR * 0.5, s: [126, 126] },
            { t: DUR, s: [100, 100] },
          ],
          6,
        ),
        o: av(
          [
            { t: 0, s: [100] },
            { t: DUR * 0.5, s: [74] },
            { t: DUR, s: [100] },
          ],
          11,
        ),
      }),
    ),
  );

  // The knocked-out N, painted in the ground colour over the pebble.
  mono.forEach((shape, index) =>
    layers.push(
      layer(`monogram-${index + 1}`, ind++, fillGroup(shapeProp(shape), CREAM_RGB), transform({ s: monoScale })),
    ),
  );

  layers.push(
    layer(
      "pebble",
      ind++,
      fillGroup(morph, RED_RGB),
      transform({
        r: av(
          [
            { t: 0, s: [0] },
            { t: DUR * 0.5, s: [3] },
            { t: DUR, s: [0] },
          ],
          10,
        ),
      }),
    ),
  );

  // Ripple rings behind the pebble, offset so the field reads as continuous.
  for (let k = 0; k < 3; k++) {
    layers.push(
      layer(
        `ripple-${k + 1}`,
        ind++,
        strokeGroup(shapeProp(waves[k % waves.length]), RED_RGB, 3),
        transform({
          s: av(
            [
              { t: 0, s: [100 + k * 42, 100 + k * 42] },
              { t: DUR, s: [214 + k * 42, 214 + k * 42] },
            ],
            6,
          ),
          o: av(
            [
              { t: 0, s: [52 - k * 14] },
              { t: DUR * 0.72, s: [0] },
              { t: DUR, s: [0] },
            ],
            11,
          ),
          r: av(
            [
              { t: 0, s: [0] },
              { t: DUR, s: [k % 2 === 0 ? 12 : -12] },
            ],
            10,
          ),
        }),
      ),
    );
  }

  return {
    v: "5.9.6",
    fr: FPS,
    ip: 0,
    op: DUR,
    w: SIZE,
    h: SIZE,
    nm: "net sale — pebble wave",
    ddd: 0,
    assets: [],
    layers,
    markers: [],
  };
}

function writeLottie() {
  const dir = join(ROOT, "public", "lottie");
  mkdirSync(dir, { recursive: true });
  const data = buildLottie();
  const file = join(dir, "net-sale-wave.json");
  writeFileSync(file, JSON.stringify(data));
  return { file, layers: data.layers.length };
}

/* ========================================================================== */

const svgCount = writeSvgs();
writePathsModule();
const lottie = writeLottie();

console.log(`net sale brand assets generated:
  ${svgCount} SVG marks      -> public/brand/
  1 path module     -> src/components/brand/paths.ts
  1 Lottie (${lottie.layers} layers) -> public/lottie/net-sale-wave.json`);
